server:
  port: 15550
  servlet:
    context-path: /home

#spring: # < конфигурируем спринг-окружение
#  datasource: # < спринговый стандартный бин для подключения к базе данных
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
#    username: root
#    password: 1
#  jpa: # < указываем реализацию JPA (по умолчанию будет подключен хибер-т)
#    show-sql: true # < показывать сгенерированные запросы хибер-та
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect

spring:
  datasource: # < спринговый стандартный бин для подключения к базе данных
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?user=root&password=1
#    url: jdbc:mysql://localhost:3306/smarthome.sql
    url: jdbc:mysql://localhost:3306/smarthome
    username: root
    password: 1
  jpa: # < указываем реализацию JPA (по умолчанию будет подключен хибер-т)
    show-sql: false # < показывать сгенерированные запросы хибер-та
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5Dialect
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # мля!..
        # диалекты: https://docs.jboss.org/hibernate/orm/3.5/javadocs/org/hibernate/dialect/package-summary.html#package_description

jwt:
  secret: $2a$12$c4HYjryn7vo1bYQfSzkUDe8jPhYIpInbUKZmv5lGnmcyrQPLIWnVu
  lifetime: 36000000 #10ч
#https://jwt.io/